---
book_repo: docs-book-csb-gcp
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: 'edge'

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:

# cross-product resources
- repository:
    name: pivotal-cf/docs-partials
    ref: master
  directory: csb-gcp/partials
  no_docs: true

- repository:
    name: pivotal-cf/docs-csb-gcp
    ref: 'master'
  directory: csb-gcp/1-n
  subnav_template: csb-gcp_subnav_1-n.erb
  product_info:
    use_local_header: true
    latest_stable_version: '1.0'
    changelog_href: http://docs.pivotal.io/csb-gcp/1-n/release-notes.html/
    local_header_img: /images/cloud_rings.png
    local_header_title: Tanzu Cloud Service Broker for GCP
    search_placeholder: Search Cloud Service Broker for GCP
    url_prefix: csb-gcp/1-n
    local_product_version: '1.0'
    local_header_links: []
    local_header_version_list:
